engines:
  eslint:
    enabled: true
    channel: "eslint-6"
    config:
      extensions:
      - .mjs
  fixme:
    enabled: true
  # Waiting on https://github.com/nodesecurity/nsp/pull/142 to support yarn.lock
  nodesecurity:
    enabled: false
  markdownlint:
    enabled: true
    checks:
      MD024:
        enabled: false
      MD033:
        enabled: false
  shellcheck:
    enabled: true
ratings:
  paths:
  - "**.js"
  - "**.md"
  - "**.sh"
exclude_patterns:
- ".vscode/"
- "CHANGELOG.md"
